### ISSUE TITLE
AutoPi

### ISSUE THREAD

**Issue by Dinth** [alexanv1/customcomponents#2]
Hi. I just wanted to say that im really excited about seeing someone developing an AutoPi integration for HA! I have been trying to do that myself in the past, but without any coding experience, i have failed miserably :( 
Is your custom component working yet? I would happy to give it a test!

**Comment by alexanv1** [comment]
Hi! Yeah, the custom integration is working and I have been using it with minimal issues for over a year. I didn't announce\advertise it though since I don't really have the time to support it for a large number of folks :)

Just copy all files from autopi folder to custom_components\autopi in your Home Assistant installation and restart HA. You should then be able to select AutoPi from the integrations list and go through the config flow to enter your username\password (keep in mind that password is stored in cleartext in HA config files)

That said, integration is pretty basic and I really only created it to use a vehicle device_tracker. It exposes a few additional sensors (speed, RPM, fuel level, etc) but nothing beyond that.

**Comment by Dinth** [comment]
Amazing it seems to work! Great work, really hugely appreciated (i was literally meant to sell my AutoPi for the tiny chunk of its value, because i couldnt make it work with Home Assistant!).
If you will be planning to maintain this plugin, please also set up sponsorship on Github so we can buy you a beer or coffee :) 

Personally the only thing i am missing in this plugin is battery level/voltage which i would love to see - but no pressure :)

**Comment by alexanv1** [comment]
Heh, battery voltage is actually useful for me too so thanks for making me realize that it's available via the cloud API
(I honestly have no idea how I didn't realize that :))

Anyway, I just pushed an update that adds the sensors for battery level and voltage. You will need to copy the files over and restart HA.

I also had to make a change to reduce the frequency of attribute updates. Every sensor\attribute is a separate call to AutoPi's API and retrieving so many attributes was slowing down the device_tracker update too much (and I really need the device tracker update to be quick since I use it to open garage doors). Anyway, position will now update every 10 seconds and the rest of the attributes every 60 seconds. If you need to tweak the values, I can tell you how to tweak them in the code in your copy of the custom integration.

Now that I am messing with the code again, next thing I plan to do is switch to async updates so that multiple AutoPi devices can be updated in parallel (and possibly so that attributes can be retrieved in parallel as well).
